CREATE TABLE notes(
    /* ID AUTOINCREMENTAL PARA LAS NOTAS CREADAS*/
    id INT NOT NULL AUTO_INCREMENT,
    /*vALOR UNICO NO CONSECUTIVO PARA NAVEGAR ENTRE NOTAS*/
    uuid VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    updated DATE NOT NULL,
    PRIMARY KEY (id)
)

